[package]
edition = "2021"
name = "rxing"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "3.8.6", default-features = false, features = ["napi4"] }
napi-derive = "3.5.5"
image = "=0.25.8"
rxing = {version = "~0.9.0", features = ["image", "svg_read", "svg_write"] }
data-url = "0.3.2"
base64 = "0.22.1"

[build-dependencies]
napi-build = "2.3.1"

[profile.release]
lto = true
