/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum BarcodeFormat {
  /** Aztec 2D barcode format.  */
  AZTEC = 0,
  /** CODABAR 1D format.  */
  CODABAR = 1,
  /** Code 39 1D format.  */
  Code39 = 2,
  /** Code 93 1D format.  */
  Code93 = 3,
  /** Code 128 1D format.  */
  Code128 = 4,
  /** Data Matrix 2D barcode format.  */
  DataMatrix = 5,
  /** EAN-8 1D format.  */
  Ean8 = 6,
  /** EAN-13 1D format.  */
  Ean13 = 7,
  /** ITF (Interleaved Two of Five) 1D format.  */
  ITF = 8,
  /** MaxiCode 2D barcode format.  */
  MAXICODE = 9,
  /** PDF417 format.  */
  Pdf417 = 10,
  /** QR Code 2D barcode format.  */
  QrCode = 11,
  /** RSS 14  */
  Rss14 = 12,
  /** RSS EXPANDED  */
  RssExpanded = 13,
  /** UPC-A 1D format.  */
  UpcA = 14,
  /** UPC-E 1D format.  */
  UpcE = 15,
  /** UPC/EAN extension format. Not a stand-alone format.  */
  UpcEanExtension = 16,
  /** */
  UnsupportedFormat = 17
}
export interface EncodeOptions {
  barcodeFormat?: BarcodeFormat
  width?: number
  height?: number
  margin?: number
  errorCorrection?: string
  characterSet?: string
  dataMatrixCompact?: boolean
  pdf417Compact?: boolean
  pdf417Compaction?: string
  pdf417AutoEci?: boolean
  aztecLayers?: number
  qrVersion?: string
  qrMaskPattern?: string
  qrCompact?: boolean
  gs1Format?: boolean
  forceCodeSet?: string
  forceC40?: boolean
  code128Compact?: boolean
  outputFile?: string
}
/**
 * Encode a barcode from a string, returning a buffer representing the image
 *
 * @param {string} data The data to encode
 * @param {EncodeOptions} [options] Optional options to pass to the encoder
 *
 * @returns {Buffer|null} A buffer representing the encoded barcode, or `null` if the barcode could not be encoded or encountered an error
 *
 * @example
 * const { encode } = require('@rxing/rxing');
 * const fs = require('fs');
 *
 * const data = 'Hello World!';
 * const buffer = encode(data);
 * fs.writeFileSync('hello-world.png', buffer);
*/
export function encode(data: string, options?: EncodeOptions | undefined | null): Buffer | null
export interface DecodeOptions {
  tryHarder?: boolean
  decodeMulti?: boolean
  barcodeFormat?: Array<BarcodeFormat>
  pureBarcode?: boolean
  characterSet?: string
  allowedLengths?: Array<number>
  assumeCode39CheckDigit?: boolean
  assumeGs1?: boolean
  returnCodabarStartEnd?: boolean
  allowedEanExtensions?: Array<number>
  alsoInverted?: boolean
  other?: string
}
export interface DecodeResult {
  text: string
  rawBytes: Array<number>
  numBits: number
  format: BarcodeFormat
}
/**
 * Decode a barcode from a file or base64 string
 *
 * @param {string} input Either a path to a file or a base64 string
 * @param {DecodeOptions} [options] Optional options to pass to the decoder
 *
 * @returns {DecodeResult|Array<DecodeResult>|null} The decode result or a list of decode results if `options.decodeMulti` is set to `true`, or `null` if the barcode could not be decoded or encountered an error
 *
 * @example
 * const { decode } = require('@rxing/rxing');
 * const result = decode('path/to/file.png');
 * console.log(result.text);
 * // Or
 * const result = decode('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA');
 * console.log(result.text);
*/
export function decode(input: string, options?: DecodeOptions | undefined | null): DecodeResult | Array<DecodeResult> | null
