/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum BarcodeFormat {
  /** Aztec 2D barcode format.  */
  AZTEC = 0,
  /** CODABAR 1D format.  */
  CODABAR = 1,
  /** Code 39 1D format.  */
  Code39 = 2,
  /** Code 93 1D format.  */
  Code93 = 3,
  /** Code 128 1D format.  */
  Code128 = 4,
  /** Data Matrix 2D barcode format.  */
  DataMatrix = 5,
  /** EAN-8 1D format.  */
  Ean8 = 6,
  /** EAN-13 1D format.  */
  Ean13 = 7,
  /** ITF (Interleaved Two of Five) 1D format.  */
  ITF = 8,
  /** MaxiCode 2D barcode format.  */
  MAXICODE = 9,
  /** PDF417 format.  */
  Pdf417 = 10,
  /** QR Code 2D barcode format.  */
  QrCode = 11,
  /** RSS 14  */
  Rss14 = 12,
  /** RSS EXPANDED  */
  RssExpanded = 13,
  /** UPC-A 1D format.  */
  UpcA = 14,
  /** UPC-E 1D format.  */
  UpcE = 15,
  /** UPC/EAN extension format. Not a stand-alone format.  */
  UpcEanExtension = 16,
  /** */
  UnsupportedFormat = 17
}
export interface EncodeOptions {
  barcodeFormat?: BarcodeFormat
  width?: number
  height?: number
  margin?: number
  errorCorrection?: string
  characterSet?: string
  dataMatrixCompact?: boolean
  pdf417Compact?: boolean
  pdf417Compaction?: string
  pdf417AutoEci?: boolean
  aztecLayers?: number
  qrVersion?: string
  qrMaskPattern?: string
  qrCompact?: boolean
  gs1Format?: boolean
  forceCodeSet?: string
  forceC40?: boolean
  code128Compact?: boolean
  outputFile?: string
}
export function encode(data: string, options?: EncodeOptions | undefined | null): Buffer | null
export interface DecodeOptions {
  tryHarder?: boolean
  decodeMulti?: boolean
  barcodeFormat?: Array<BarcodeFormat>
  pureBarcode?: boolean
  characterSet?: string
  allowedLengths?: Array<number>
  assumeCode39CheckDigit?: boolean
  assumeGs1?: boolean
  returnCodabarStartEnd?: boolean
  allowedEanExtensions?: Array<number>
  alsoInverted?: boolean
  other?: string
}
export interface DecodeResult {
  text: string
  rawBytes: Array<number>
  numBits: number
  format: BarcodeFormat
}
export function decode(fileName: string, options?: DecodeOptions | undefined | null): DecodeResult | Array<DecodeResult> | null
